#!/bin/bash

beep

# this event is tuned for Canon LiDE 210
#
# scans into a (multipage) PDF document:
# - on first 'file' button press, creates a 1-page PDF document
# - on each following 'file' button press, adds next page to the PDF document
# - scanning of the current PDF document stops after pressing 'extra' button or 10 minutes after the last # page was scanned
# - scanning of a multipage PDF document is not aborted if other buttons are pressed between pages # (e.g. copy)
#
# default settings: color image, 200 dpi, size A4, automatically deskew and despeckle
# NOTE: these settings require 25 MB of disk space in /tmp per page
#
# dependencies:
# libtiff-tools (tiff2pdf, tiffcp)

# contrast and despeckle removes noise in mostly white documents and result in much smaller PDF size
SCAN_SETTINGS="--mode color -x 210 -y 297 --contrast 16 --brightness 6 --swdeskew=yes --swcrop=yes --swdespeck=yes --despeck 1 --resolution 150"
#SCAN_SETTINGS="--mode color -x 210 -y 297 --contrast 0 --brightness 0 --swdeskew=yes --swcrop=no --swdespeck=no --resolution 1200 --lamp-off-scan=yes"

# JPEG compression (-j) with quality (-q) 85 produces good quality at acceptable size, too small quality values can produce artefacts
PDF_SETTINGS="-p A4 -j -q 90"

# output file settings
PDF_TITLE="Scan $(date '+%Y-%m-%d %H:%M:%S')"
OUTFILE="$HOME/scans/scan-$(date '+%Y-%m-%d_%H-%M-%S').pdf"

# during timeout (in seconds) after the last page was scanned, next scan will append another page
# after the timeout, button 'file' will create a new PDF document even if button 'extra' was not pressed
TIMEOUT="600"


# internal variables, don't change
TMPFILE_PAGE="/tmp/multipage-scan-page.tiff"
TMPFILE_PAGE_PDF="/tmp/multipage-scan-page.pdf"
TMPFILE_TESSERACT="/tmp/tessout.osd"
LOCKFILE="/tmp/insaned-scan.lock"
INSANED_LOGFILE="/tmp/insaned.log"
DEVICE="$1"

# first line of MULTIPAGE_LOCK file contains file name of the current document
# last line of MULTIPAGE_LOCK file contains UNIX timestamp when the last scan was finished
# the number of lines in MULTIPAGE_LOCK is the number of scanned pages - 1
MULTIPAGE_LOCK="/tmp/insaned-multipage.lock"


# scans one page and appends it to the multipage TIFF file
# param 1: PDF output file
# shellcheck disable=SC2086
scanNextPage() {
    scanimage --device-name "$DEVICE" --format tiff $SCAN_SETTINGS > "$TMPFILE_PAGE"

    
    #Tesseract auto rotation stuff. Causes a VERY large performance drop.
    #TODO Get tesseract to run while the scanner runs. May require a total rewrite to replace scanimage and use pyinsane instead.
    tesseract "$TMPFILE_PAGE" "$TMPFILE_TESSERACT" -psm 0
    rotate=$(grep -oP '(?<=Rotate: ).*' "$TMPFILE_TESSERACT")
    tiffcrop -R "$(rotate)" "$TMPFILE_PAGE"
    
    tiff2pdf $PDF_SETTINGS -t "$PDF_TITLE" -F -o "$TMPFILE_PAGE_PDF" "$TMPFILE_PAGE" >> "$INSANED_LOGFILE" 2>&1
    
    if [ ! -f "$1" ]; then	
    	cp "$TMPFILE_PAGE_PDF" "$1"
    	echo first page
    else
    	pdfunite "$1" "$TMPFILE_PAGE_PDF" "$1"tmp
    	mv "$1"tmp "$1"
    	echo multipage
    fi
    
    #tiffcp -a "$TMPFILE_PAGE" "$TMPFILE_ALL" >> "$INSANED_LOGFILE" 2>&1
    #tiff2pdf $PDF_SETTINGS -t "$PDF_TITLE" -F -o "$1" "$TMPFILE_PAGE" >> "$INSANED_LOGFILE" 2>&1
}


# lock file is needed to avoid collisions with other events
if [ -f "$LOCKFILE" ]; then
    echo "Error: Another scanning operation is currently in progress" >> "$INSANED_LOGFILE"
    exit 0
fi
# cleanup on exit
finish() {
    rm -f "$LOCKFILE" >/dev/null 2>&1
}
trap finish EXIT
touch "$LOCKFILE"


# if the MULTIPAGE_LOCK file exists: check for timeout
if [ -f "$MULTIPAGE_LOCK" ]; then
    TIME_PASSED=$(($(date '+%s') - $(tail -1 "$MULTIPAGE_LOCK")))
    if test "$TIME_PASSED" -gt "$TIMEOUT"; then
        echo "finished scanning multipage document on timeout: $(head -1 "$MULTIPAGE_LOCK")" >> "$INSANED_LOGFILE"
        rm -f "$MULTIPAGE_LOCK" >> "$INSANED_LOGFILE" 2>&1
    fi
fi

if [ ! -f "$MULTIPAGE_LOCK" ]; then
    # first press: no MULTIPAGE_LOCK file exists yet

    # create multipage lock
    echo "$OUTFILE" > "$MULTIPAGE_LOCK"
    echo "started scanning multipage document: $OUTFILE" >> "$INSANED_LOGFILE"

    # clean up previous pages
    rm -f "$TMPFILE_PAGE" "$TMPFILE_PAGE_PDF" >> "$INSANED_LOGFILE" 2>&1
else
    # consequent press: MULTIPAGE_LOCK file exist

    # get the correct file name
    OUTFILE="$(head -1 "$MULTIPAGE_LOCK")"
    echo "scanning next page of multipage document: $OUTFILE" >> "$INSANED_LOGFILE"
fi

# scan
scanNextPage "$OUTFILE"

# add timestamp to the MULTIPAGE_LOCK file
date '+%s' >> "$MULTIPAGE_LOCK"

#beep

